development:
  adapter: postgresql
  encoding: unicode
  database: 
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: 
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: 
  username:
  password:
